alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# ----- Window Focus -----# 
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# ----- Window Positioning -----# 
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-ctrl-h = ['join-with left', 'mode main']
alt-shift-ctrl-j = ['join-with down', 'mode main']
alt-shift-ctrl-k = ['join-with up', 'mode main']
alt-shift-ctrl-l = ['join-with right', 'mode main']

alt-shift-backtick = "layout floating tiling"  # toggle float/tile mode of current window
alt-shift-enter = "balance-sizes"              # balance sizes of all windows on current space
alt-shift-backspace = "flatten-workspace-tree" # "reset" current workspace layout
alt-tab = "focus-back-and-forth"
alt-down = "focus-monitor down"
alt-up = "focus-monitor up"

# ----- Window Sizes -----# 
alt-shift-minus = 'resize smart -200'
alt-shift-equal = 'resize smart +200'
alt-shift-m = "fullscreen"
