alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-cmd-h = ['join-with left', 'mode main']
alt-cmd-j = ['join-with down', 'mode main']
alt-cmd-k = ['join-with up', 'mode main']
alt-cmd-l = ['join-with right', 'mode main']

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-shift-m = "fullscreen"
alt-shift-n = "layout floating tiling"


