alt-1 = 'workspace 1'
alt-q = 'workspace Q'
alt-a = 'workspace A'

alt-2 = 'workspace 2'
alt-w = 'workspace W'
alt-s = 'workspace S'

alt-3 = 'workspace 3'
alt-e = 'workspace E'
alt-d = 'workspace D'

alt-4 = 'workspace 4'
alt-r = 'workspace R'
alt-f = 'workspace F'

alt-5 = 'workspace 5'
alt-t = 'workspace T'
alt-g = 'workspace G'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-a = 'move-node-to-workspace A'

alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-s = 'move-node-to-workspace S'

alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-e = 'move-node-to-workspace E'
alt-shift-d = 'move-node-to-workspace D'

alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-r = 'move-node-to-workspace R'
alt-shift-f = 'move-node-to-workspace F'

alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-t = 'move-node-to-workspace T'
alt-shift-g = 'move-node-to-workspace G'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
alt-shift-semicolon = 'mode service'

[workspace-to-monitor-force-assignment]
1 = ['secondary', 'main']
2 = ['secondary', 'main']
3 = ['secondary', 'main']
4 = ['secondary', 'main']
5 = ['secondary', 'main']


