name: core
services:

  # traefik:
  #   container_name: traefik
  #   image: traefik:v2.11
  #   restart: unless-stopped
  #   #privileged: true
  #   environment:
  #     - TZ=${TZ}
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #   command:
  #     - --log.level=DEBUG
  #     - --api.dashboard=true
  #     - --api.insecure=true
  #     - --providers.docker=true
  #     - --providers.docker.exposedbydefault=false
  #     - --entrypoints.websecure.address=:443
  #     - --certificatesresolvers.resolver.acme.tlschallenge=true
  #     - --certificatesresolvers.resolver.acme.email=${ADMIN_EMAIL}
  #     - --certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json
  #   ports:
  #     - "1443:443"
  #     - "8080:8080" # traefik dashboard
  #   volumes:
  #     - ${APP_DATA}/webservices/letsencrypt:/letsencrypt
  #     #- /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /var/run/podman/podman.sock:/var/run/docker.sock:ro

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - URL=${ROOT_DOMAIN}
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - SUBDOMAINS=wildcard
      - ONLY_SUBDOMAINS=true
    volumes:
      - ${APP_DATA}/webservices/swag/config:/config
      - ./nginx-sites:/sites
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped

  # portainer:
  #   container_name: portainer
  #   image: portainer/portainer-ce:latest
  #   restart: unless-stopped
  #   #privileged: true
  #   environment:
  #     - TZ=${TZ}
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #   volumes:
  #     - /var/run/podman/podman.sock:/var/run/docker.sock:ro
  #     - ${APP_DATA}/webservices/portainer:/data
  #   ports:
  #     - "9000:9000"
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.portainer.rule=Host(`portainer.${ROOT_DOMAIN}`)
    #   - traefik.http.routers.portainer.tls=true
    #   - traefik.http.routers.portainer.entrypoints=websecure
    #   - traefik.http.routers.portainer.tls.certresolver=resolver
    #   - traefik.http.services.portainer.loadbalancer.server.port=9000