name: games
services:

  factorio:
    image: factoriotools/factorio:stable
    container_name: factorio
    restart: unless-stopped
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - ${APP_DATA}/gameservers/factorio:/factorio
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UPDATE_MODS_ON_START=true
#      - USERNAME=FactorioUsername
#      - TOKEN=FactorioToken
#      - PORT=34198
#      - PRESET=deathworld
#      - ADDR=::1
