alt-shift-semicolon = 'mode service'

[workspace-to-monitor-force-assignment]
1 = ['secondary', 'main']
2 = ['secondary', 'main']
3 = ['secondary', 'main']
4 = ['secondary', 'main']
5 = ['secondary', 'main']
