cmd-alt-1 = 'workspace 1'
cmd-alt-q = 'workspace Q'
cmd-alt-a = 'workspace A'

cmd-alt-2 = 'workspace 2'
cmd-alt-w = 'workspace W'
cmd-alt-s = 'workspace S'

cmd-alt-3 = 'workspace 3'
cmd-alt-e = 'workspace E'
cmd-alt-d = 'workspace D'

cmd-alt-4 = 'workspace 4'
cmd-alt-r = 'workspace R'
cmd-alt-f = 'workspace F'

cmd-alt-5 = 'workspace 5'
cmd-alt-t = 'workspace T'
cmd-alt-g = 'workspace G'

cmd-shift-alt-1 = 'move-node-to-workspace 1'
cmd-shift-alt-q = 'move-node-to-workspace Q'
cmd-shift-alt-a = 'move-node-to-workspace A'

cmd-shift-alt-2 = 'move-node-to-workspace 2'
cmd-shift-alt-w = 'move-node-to-workspace W'
cmd-shift-alt-s = 'move-node-to-workspace S'

cmd-shift-alt-3 = 'move-node-to-workspace 3'
cmd-shift-alt-e = 'move-node-to-workspace E'
cmd-shift-alt-d = 'move-node-to-workspace D'

cmd-shift-alt-4 = 'move-node-to-workspace 4'
cmd-shift-alt-r = 'move-node-to-workspace R'
cmd-shift-alt-f = 'move-node-to-workspace F'

cmd-shift-alt-5 = 'move-node-to-workspace 5'
cmd-shift-alt-t = 'move-node-to-workspace T'
cmd-shift-alt-g = 'move-node-to-workspace G'

alt-shift-semicolon = 'mode service'

[workspace-to-monitor-force-assignment]
1 = ['secondary', 'main']
2 = ['secondary', 'main']
3 = ['secondary', 'main']
4 = ['secondary', 'main']
5 = ['secondary', 'main']
