name: llm
services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: always
    hostname: ollama
    user: "${UID:-1000}:${GID:-100}"
    environment:
      TZ: ${HOSTING_TZ}
      OLLAMA_KEEP_ALIVE: 24h
      HOME: /home/ollama
    volumes:
      - ${APPDATA_PATH}/llm/ollama:/home/ollama/.ollama:U
    devices:
      - nvidia.com/gpu=all
    labels:
      - traefik.enable=true
      - traefik.http.routers.ollama.rule=Host(`ollama.${HOSTNAME}.${HOSTING_ROOT}`)
      - traefik.http.routers.ollama.tls=true
      - traefik.http.routers.ollama.entrypoints=websecure
      - traefik.http.routers.ollama.tls.certresolver=resolver
      - traefik.http.services.ollama.loadbalancer.server.port=11434

  litellm-postgres:
    container_name: litellm-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${HOSTING_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${HOSTING_ADMIN_PASSWORD}
      POSTGRES_DB: litellm
    volumes:
      - ${APPDATA_PATH}/llm/litellm-postgres:/var/lib/postgresql/data:U

  litellm:
    container_name: litellm
    restart: always
    image: ghcr.io/berriai/litellm:main-latest
    depends_on:
      - litellm-postgres
    environment:
      LITELLM_MASTER_KEY: ${HOSTING_COMMON_MASTER_KEY}
      OPENROUTER_API_KEY: ${HOSTING_OPENROUTER_API_KEY}
      UI_USERNAME: ${HOSTING_ADMIN_USERNAME}
      UI_PASSWORD: ${HOSTING_ADMIN_PASSWORD}
      DATABASE_URL: postgresql://${HOSTING_ADMIN_USERNAME}:${HOSTING_ADMIN_PASSWORD}@litellm-postgres:5432/litellm
      LITELLM_LOG: ERROR
      JSON_LOGS: "True"
    volumes:
      - ${APPCONF_PATH}/llm/litellm/config:/config:U
    command:
      - --config=/config/config.yaml
    labels:
      - traefik.enable=true
      - traefik.http.routers.litellm.rule=Host(`litellm.${HOSTNAME}.${HOSTING_ROOT}`)
      - traefik.http.routers.litellm.tls=true
      - traefik.http.routers.litellm.entrypoints=websecure
      - traefik.http.routers.litellm.tls.certresolver=resolver
      - traefik.http.services.litellm.loadbalancer.server.port=4000

  librechat-api:
    container_name: librechat-api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    depends_on:
      - librechat-mongodb
      - librechat-rag-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JWT_SECRET: ${HOSTING_LIBRECHAT_JWT_SECRET}
      JWT_REFRESH_SECRET: ${HOSTING_LIBRECHAT_JWT_REFRESH_SECRET}
      MEILI_MASTER_KEY: ${HOSTING_COMMON_MASTER_KEY}
      LITELLM_MASTER_KEY: ${HOSTING_COMMON_MASTER_KEY}
      OPENROUTER_API_KEY: ${HOSTING_OPENROUTER_API_KEY}
      CREDS_KEY: ${HOSTING_LIBRECHAT_CREDS_KEY}
      CREDS_IV: ${HOSTING_LIBRECHAT_CREDS_IV}
      DOMAIN_CLIENT: https://librechat.${HOSTNAME}.${HOSTING_ROOT}
      DOMAIN_SERVER: https://librechat.${HOSTNAME}.${HOSTING_ROOT}
      MONGO_URI: mongodb://librechat-mongodb:27017/LibreChat
      MEILI_HOST: http://librechat-meilisearch:7700
      EMBEDDINGS_PROVIDER: huggingface
      EMBEDDINGS_MODEL: sentence-transformers/all-MiniLM-L6-v2
      RAG_API_URL: http://librechat-rag-api:8000
      ALLOW_REGISTRATION: true
    volumes:
      - ${APPCONF_PATH}/llm/librechat/librechat.yaml:/app/librechat.yaml
      - ${APPDATA_PATH}/llm/librechat/images:/app/client/public/images:U
      - ${APPDATA_PATH}/llm/librechat/uploads:/app/uploads:U
      - ${APPDATA_PATH}/llm/librechat/logs:/app/logs:U
    labels:
      - traefik.enable=true
      - traefik.http.routers.librechat.rule=Host(`librechat.${HOSTNAME}.${HOSTING_ROOT}`)
      - traefik.http.routers.librechat.tls=true
      - traefik.http.routers.librechat.entrypoints=websecure
      - traefik.http.routers.librechat.tls.certresolver=resolver
      - traefik.http.services.librechat.loadbalancer.server.port=3080

  librechat-mongodb:
    container_name: librechat-mongodb
    image: mongo
    restart: always
    volumes:
      - ${APPDATA_PATH}/llm/librechat/data-node:/data/db:U
    command: mongod --noauth

  librechat-meilisearch:
    container_name: librechat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    environment:
      MEILI_HOST: http://librechat-meilisearch:7700
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${HOSTING_COMMON_MASTER_KEY}
    volumes:
      - ${APPDATA_PATH}/llm/librechat/meili_data_v1.12:/meili_data:U

  librechat-vectordb:
    container_name: librechat-vectordb
    image: pgvector/pgvector:0.8.0-pg15-trixie
    restart: always
    environment:
      POSTGRES_DB: librechatpostgresdb
      POSTGRES_USER: ${HOSTING_ADMIN_USERNAME}
      POSTGRES_PASSWORD: ${HOSTING_ADMIN_PASSWORD}
    volumes:
      - ${APPDATA_PATH}/llm/librechat/pgdata:/var/lib/postgresql/data:U

  librechat-rag-api:
    container_name: librechat-rag-api
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    restart: always
    depends_on:
      - librechat-vectordb
    environment:
      DB_HOST: librechat-vectordb
      RAG_PORT: 8000
      EMBEDDINGS_PROVIDER: huggingface
      EMBEDDINGS_MODEL: sentence-transformers/all-MiniLM-L6-v2
