name: home

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${APPDATA_PATH}/home/mosquitto/config:/mosquitto/config:U
      - ${APPDATA_PATH}/home/mosquitto/data:/mosquitto/data:U
      - ${APPDATA_PATH}/home/mosquitto/log:/mosquitto/log:U
    labels:
      - traefik.enable=true
      - traefik.http.routers.mqtt.rule=Host(`mqtt.${HOSTNAME}.${HOSTING_ROOT}`)
      - traefik.http.routers.mqtt.tls=true
      - traefik.http.routers.mqtt.entrypoints=websecure
      - traefik.http.routers.mqtt.tls.certresolver=resolver
      - traefik.http.services.mqtt.loadbalancer.server.port=9001

  owntracks:
    container_name: owntracks
    image: owntracks/recorder
    restart: always
    environment:
      - OTR_HOST=mqtt
    ports:
      - 8083:8083
    volumes:
      - ${APPDATA_PATH}/home/owntracks/store:/store:U
      - ${APPDATA_PATH}/home/owntracks/config:/config:U
    depends_on:
      - mqtt
    labels:
      - traefik.enable=true
      - traefik.http.routers.owntracks.rule=Host(`owntracks.${HOSTNAME}.${HOSTING_ROOT}`)
      - traefik.http.routers.owntracks.tls=true
      - traefik.http.routers.owntracks.entrypoints=websecure
      - traefik.http.routers.owntracks.tls.certresolver=resolver
      - traefik.http.services.owntracks.loadbalancer.server.port=8083

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.4.1
    environment:
      REDIS_HOSTNAME: immich_redis
      DB_HOSTNAME: immich_db
      DB_DATABASE_NAME: immich
      DB_USERNAME: ${HOSTING_ADMIN_USERNAME}
      DB_PASSWORD: ${HOSTING_ADMIN_PASSWORD}
    volumes:
      - ${APPDATA_PATH}/home/immich/upload:/usr/src/app/upload:U
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich_redis
      - immich_db
    ports:
      - 2283:2283
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`immich.${HOSTNAME}.${HOSTING_ROOT}`)
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls.certresolver=resolver
      - traefik.http.services.immich.loadbalancer.server.port=2283

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich_redis:
    container_name: immich_redis
    image: docker.io/redis:7.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich_db:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${HOSTING_ADMIN_PASSWORD}
      POSTGRES_USER: ${HOSTING_ADMIN_USERNAME}
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${APPDATA_PATH}/home/immich/postgres:/var/lib/postgresql/data:U
    healthcheck:
      test: pg_isready --dbname='immich' || exit 1; Chksum="$$(psql --dbname='immich' --username='${HOSTING_ADMIN_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on",
      ]
    restart: always

volumes:
  model-cache:
