set -g mouse on
set -g default-terminal "screen-256color"
set -g terminal-overrides ",xterm-256color:RGB"
set -g default-shell "$SHELL"
set -g extended-keys on
set -g @window_name ' #(cd "#{pane_current_path}" && top=$(git rev-parse --show-toplevel 2>/dev/null); if [ -n "$top" ]; then repo=$(basename "$top"); branch=$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null); if [ -n "$branch" ]; then echo "$repo [$branch]"; else echo "$repo"; fi; else basename "#{pane_current_path}"; fi)'

#--------- Window & Pane ---------#
set -g base-index 1
setw -g pane-base-index 1

# Pane resizing
bind Space select-layout tiled
bind = select-layout even-horizontal
bind | select-layout even-vertical

# Key bindings for pane splitting using Ctrl+HJKL
bind C-h split-window -h -c "#{pane_current_path}" -b
bind C-l split-window -h -c "#{pane_current_path}"
bind C-j split-window -v -c "#{pane_current_path}"
bind C-k split-window -v -c "#{pane_current_path}" -b

# Resize Panes
bind -r h resize-pane -L 25
bind -r l resize-pane -R 25
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5

# Focus Panes
bind -r H swap-pane -s '{left-of}'
bind -r L swap-pane -s '{right-of}'
bind -r J swap-pane -s '{down-of}'
bind -r K swap-pane -s '{up-of}'

# Focus Tabs
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

# ----- Status bar styling ----- #
set -g status on
set -g status-justify centre
set -g status-left-length 50
set -g status-right-length 150
set -g status-style bg=default,fg=white
set -g status-position top

# ----- Pane styling ----- #
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

#--------- Session Hopping ---------#
bind-key "S" run-shell "sesh_browser"
bind-key "Q" kill-session
