{
  inputs,
  lib,
  ...
}:
let
  hyprland = inputs.wrapper-modules.lib.wrapModule ../../wrappers/hyprland.nix;

  luaString = builtins.toJSON;
in
{
  modules.nixos.hyprland =
    {
      config,
      pkgs,
      ...
    }:
    let
      apps = config.user.apps;
      cfg = config.hyprland;

      luaMonitorConfig = lib.concatStringsSep "\n" (
        lib.mapAttrsToList (
          name: output:
          let
            mode = output.mode or "preferred";
            position = output.position or "auto";
            scale = output.scale or 1;
          in
          "hl.monitor({ output = ${luaString name}, mode = ${luaString mode}, position = ${luaString position}, scale = ${toString scale} })"
        ) cfg.outputs
      );

      luaConfigBefore = ''
        mod = "SUPER"
        altMod = "ALT"
        hyperMod = "SUPER + CTRL + ALT + SHIFT"
        browser = ${luaString apps.browser}
        terminal = ${luaString apps.terminal}
        termPop = terminal .. " --class popup.app"

        ${luaMonitorConfig}
      '';
    in
    {
      options.hyprland = {
        enable = lib.mkEnableOption "Hyprland setup";

        nvidia = {
          enable = lib.mkEnableOption "NVIDIA-specific Hyprland session compatibility settings";

          disableWebKitDmabufRenderer = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Disable WebKitGTK DMABUF renderer for NVIDIA Wayland sessions.";
          };
        };

        outputs = lib.mkOption {
          type = lib.types.attrs;
          default = { };
          description = "Hyprland monitor settings keyed by output name.";
        };
      };

      config = lib.mkIf cfg.enable {
        programs.hyprland = {
          enable = true;
          withUWSM = true;
          package = hyprland.wrap {
            inherit pkgs;
            launchShortcut = "de";
            nvidia = cfg.nvidia;
            nixGL.autoDetect = false;

            runtimePkgs = [
              pkgs.bluetui
              pkgs.btop
              pkgs.cliphist
              pkgs.handy
              pkgs.hyprlock
              pkgs.playerctl
              pkgs.sesh
              pkgs.wiremix
              pkgs.wl-clipboard
              pkgs.wtype
              pkgs.yazi
            ]
            ++ lib.optionals (pkgs ? podman-tui) [ pkgs.podman-tui ];

            luaConfig = {
              configBefore = luaConfigBefore;
              content = "-- generated by dendritic hyprland module";
              imports = [
                ./animations.lua
                ./keybinds.lua
              ];
            };
          };
        };

        environment.sessionVariables.NIXOS_OZONE_WL = "1";
      };
    };
}
